config/routes.rb
RapaNui::Application.routes.draw do
  

  match 'servers/:id/ping' => 'servers#ping'
  match 'servers/:id/disks' => 'servers#disks', :as => "servers_disks"
  match 'servers/telnet/:id/:p' => 'servers#telnet', :as => "servers_telnet"
  match 'servers/command/:id/:cmd' => 'servers#command', :as => "servers_command"

  root :to => "server_racks#index"

  resources :servers do
    collection do
      get :search, :telnet
    end
  end
   
  resources :accounts do
    collection do
      get :login, :logout
      post :doLogin
    end
  end
   
  resources :types

  resources :operational_systems

  resources :os

  resources :server_racks

  resources :servers
  

end

app/models/operational_system.rb
class OperationalSystem < ActiveRecord::Base
  
  has_attached_file :avatar, :styles => { :icon => "22x22>", :mini => "16x16>"}
   
  scope :all, order(:name) 
  
  validates_presence_of :name
  validates_uniqueness_of :name
  
end

app/controllers/operational_systems_controller.rb
class OperationalSystemsController < ApplicationController

  before_filter :filter

  # GET /operational_systems
  # GET /operational_systems.xml
  def index
    @operational_systems = OperationalSystem.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @operational_systems }
    end
  end

  # GET /operational_systems/1
  # GET /operational_systems/1.xml
  def show
    @operational_system = OperationalSystem.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @operational_system }
    end
  end

  # GET /operational_systems/new
  # GET /operational_systems/new.xml
  def new
    @operational_system = OperationalSystem.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @operational_system }
    end
  end

  # GET /operational_systems/1/edit
  def edit
    @operational_system = OperationalSystem.find(params[:id])
  end

  # POST /operational_systems
  # POST /operational_systems.xml
  def create
    @operational_system = OperationalSystem.new(params[:operational_system])

    respond_to do |format|
      if @operational_system.save
        format.html { redirect_to(@operational_system, :notice => 'Operational system was successfully created.') }
        format.xml  { render :xml => @operational_system, :status => :created, :location => @operational_system }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @operational_system.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /operational_systems/1
  # PUT /operational_systems/1.xml
  def update
    @operational_system = OperationalSystem.find(params[:id])

    respond_to do |format|
      if @operational_system.update_attributes(params[:operational_system])
        format.html { redirect_to(@operational_system, :notice => 'Operational system was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @operational_system.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /operational_systems/1
  # DELETE /operational_systems/1.xml
  def destroy
    @operational_system = OperationalSystem.find(params[:id])
    @operational_system.destroy

    respond_to do |format|
      format.html { redirect_to(operational_systems_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/operational_systems_helper.rb
module OperationalSystemsHelper
end

app/views/operational_systems/_form.html.erb
<%= form_for @operational_system, :html => { :multipart => true } do |f| %>
  <% if @operational_system.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@operational_system.errors.count, "error") %> prohibited this operational_system from being saved:</h2>

      <ul>
      <% @operational_system.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>

  <div class="field">
	<%= f.file_field :avatar %>
  </div>



  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/operational_systems/edit.html.erb
<h1>Editing operational_system</h1>

<%= render 'form' %>

<%= link_to 'Show', @operational_system %> |
<%= link_to 'Back', operational_systems_path %>

app/views/operational_systems/index.html.erb
<h1>Operational Systems</h1>


<br/>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @operational_systems.each do |operational_system| %>
  <tr>
    <td><%= image_tag operational_system.avatar.url %> <%= operational_system.name %> </td>
    <td><%= link_to 'Show', operational_system %></td>
    <td><%= link_to 'Edit', edit_operational_system_path(operational_system) %></td>
    <td><%= link_to 'Destroy', operational_system, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Operational system', new_operational_system_path %>

app/views/operational_systems/new.html.erb
<h1>New operational_system</h1>

<%= render 'form' %>

<%= link_to 'Back', operational_systems_path %>

app/views/operational_systems/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @operational_system.name %>
  <%= image_tag @operational_system.avatar.url %>
</p>


<%= link_to 'Edit', edit_operational_system_path(@operational_system) %> |
<%= link_to 'Back', operational_systems_path %>