config/routes.rb
RapaNui::Application.routes.draw do
  

  match 'servers/:id/ping' => 'servers#ping'
  match 'servers/:id/disks' => 'servers#disks', :as => "servers_disks"
  match 'servers/telnet/:id/:p' => 'servers#telnet', :as => "servers_telnet"
  match 'servers/command/:id/:cmd' => 'servers#command', :as => "servers_command"

  root :to => "server_racks#index"

  resources :servers do
    collection do
      get :search, :telnet
    end
  end
   
  resources :accounts do
    collection do
      get :login, :logout
      post :doLogin
    end
  end
   
  resources :types

  resources :operational_systems

  resources :os

  resources :server_racks

  resources :servers
  

end

app/models/server_rack.rb
class ServerRack < ActiveRecord::Base
  
  has_many :servers
      
  validates_presence_of :name, :location
  validates_uniqueness_of :name, :message => "Name is already in use"
    
    def temperature
    
      if( !temperature_script.nil?)
        begin
          eval(temperature_script) #OMG!
        rescue
        end
      end
    end
    
end

app/controllers/server_racks_controller.rb
class ServerRacksController < ApplicationController

   before_filter :filter
   respond_to :html, :xml
   
     
  # GET /server_racks
  # GET /server_racks.xml
  def index    
    @server_racks = ServerRack.all

    respond_with @server_racks
  end

  # GET /server_racks/1
  # GET /server_racks/1.xml
  def show
    @server_rack = ServerRack.find(params[:id])

    respond_with @server_rack
  end

  # GET /server_racks/new
  # GET /server_racks/new.xml
  def new
    @server_rack = ServerRack.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @server_rack }
    end
  end

  # GET /server_racks/1/edit
  def edit
    @server_rack = ServerRack.find(params[:id])
  end

  # POST /server_racks
  # POST /server_racks.xml
  def create
    @server_rack = ServerRack.new(params[:server_rack])

    respond_to do |format|
      if @server_rack.save
        format.html { redirect_to(@server_rack, :notice => 'Server rack was successfully created.') }
        format.xml  { render :xml => @server_rack, :status => :created, :location => @server_rack }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @server_rack.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /server_racks/1
  # PUT /server_racks/1.xml
  def update
    @server_rack = ServerRack.find(params[:id])

    respond_to do |format|
      if @server_rack.update_attributes(params[:server_rack])
        format.html { redirect_to(@server_rack, :notice => 'Server rack was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @server_rack.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /server_racks/1
  # DELETE /server_racks/1.xml
  def destroy
    @server_rack = ServerRack.find(params[:id])
    @server_rack.destroy

    respond_to do |format|
      format.html { redirect_to(server_racks_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/server_racks_helper.rb
module ServerRacksHelper
end

app/views/server_racks/_form.html.erb
<%= form_for(@server_rack) do |f| %>
  <% if @server_rack.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@server_rack.errors.count, "error") %> prohibited this server_rack from being saved:</h2>

      <ul>
      <% @server_rack.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :location %><br />
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :desc %><br />
    <%= f.text_field :desc %>
  </div>

  <div class="field">
    <%= f.label :contact_email %> (Use "," to add more e-mails)<br />
    <%= f.text_field :contact_email, :size => 100 %>
  </div>
  <div class="field">
    <%= f.label :temperature_monitor %><br />
    <%= f.check_box :temperature_monitor %>
  </div>



<div class="field">
    <%= f.label :temperature_script %><br />
    <%= f.text_area :temperature_script %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/server_racks/edit.html.erb
<h1>Editing server_rack</h1>

<%= render 'form' %>

<%= link_to 'Show', @server_rack %> |
<%= link_to 'Back', server_racks_path %>

app/views/server_racks/index.html.erb
[<a href="#" onclick="pingAll();"  data-remote="true">Ping All</a>]

<%= render 'servers/searchform' %>

<% @server_racks.each do |server_rack| %>

<!-- Rack Div -->

<div title="<%= server_rack.location %>" style="border: 1px solid #AAFFAA; width: 75%; padding: 8px; margin:5px; background-color: #EFFFEF">
  
	<div style="float:left; height:30px;">
		<span style="font-family:chunk; font-size:18px; margin:15px; padding: 5px;"><%= server_rack.name %>&nbsp;&nbsp;</span>
 		<%= link_to 'Edit', edit_server_rack_path(server_rack) %>
	</div>
	
	<div style="float:right; top:0px;">
		<span style="font-family:chunk; font-size:18px; margin:1px; padding: 1px;">
		<%= server_rack.temperature%></span>
	</div>
	<br/>
	
	<% server_rack.servers.each do |server| %>




	<!-- Server Div -->
	
		<div id="server_<%= server.id%>" title=" <%= server.desc %>" style=" padding: 10px; margin:5px; margin-bottom:0px; width: 90%; padding-left:50px; background-color: #FFFFFF">
    		
			<%= image_tag server.operational_system.avatar.url, :width => "16px", :height => "16px" %>&nbsp;
			<a class="linkcat" href="javascript:collapseServer('<%= server.id%>');">
				<span style="font-weight: bold; margin-right: 10px;"><%=server.name%></span>
 				<span style="margin-right: 10px;"><%=server.ip%></span></a>
			&nbsp;&nbsp;
			[<%= link_to 'Show', server %>]&nbsp;&nbsp;
			[<%= link_to 'Ping', server_path(server)+"/ping" , :remote => true , :class => "alive_link" %>]
			<span style="margin-left: 10px;"  id="alive<%= server.id%>"></span>
			&nbsp;
			<%= image_tag "/images/cloud.png", :width => "16px", :height => "16px", :title => "Virtual" if !server.type.name.index("Virtual").nil? %>
			
		</div>
	


	<!-- Collapse Div -->

	<div id="div_server_<%= server.id%>" class="list" style="display:none; 
		 padding: 10px; margin:5px; margin-top:0px; margin-bottom:0px; width: 90%; padding-left:50px; background-color: #FFFFFF; border-top:none;"> 
		<div style="width: 340px; float:left;padding: 5px; padding-top:0px;">
			<p><b>Services:</b>
			<% if(!server.ports.nil?)
				server.ports.split(" ").each do |port|
					serv = port.split(":")[0]
		 			port = port.split(":")[1]
		 			 %>
					<li>
						<%= serv %> @ <%= link_to port, servers_telnet_url(params = {:id => server, :p => port}), :remote => true %>  
						<span id="telnet_<%=server.id%>_<%=port%>"></span>
					</li>
					<%
				 end
				end
			%>
			</p>
					

			
			[<%= link_to 'CPU Info', servers_command_url(params = {:id => server, :cmd => "cpuinfo"}), :remote => true %>  ]	
			[<%= link_to 'Disks', servers_disks_url(server), :remote => true %>]				
			[<%= link_to 'Top', servers_command_url(params = {:id => server, :cmd => "top"}), :remote => true %>  ]	
			[<%= link_to 'Memory', servers_command_url(params = {:id => server, :cmd => "freem"}), :remote => true %>  ]	
			[<%= link_to 'Who', servers_command_url(params = {:id => server, :cmd => "who"}), :remote => true %>  ]	
			[<%= link_to 'IfConfig', servers_command_url(params = {:id => server, :cmd => "ifconfig"}), :remote => true %>  ]	
			[<%= link_to 'du', servers_command_url(params = {:id => server, :cmd => "du"}), :remote => true %>  ]	
			[<%= link_to 'uptime', servers_command_url(params = {:id => server, :cmd => "uptime"}), :remote => true %>  ]	
			[<%= link_to 'netstat', servers_command_url(params = {:id => server, :cmd => "netstat"}), :remote => true %>  ]	
						
			[<a href="javascript:animatedcollapse.hide('info_server_<%=server.id%>');">Close</a>]				
			
			
		</div>
		
		<div style="float:left;padding: 5px; width: 240px; ">

			<p>
			  <b>Type:</b>
			  <%= server.type.name %>
			</p>
			<p><b>Depends of:</b>
			  <%= link_to server.depends_from.name, server.depends_from  if(!server.depends_from.nil?)  %>
			</p>
			
			<p><b>Description:</b>
			  <%= server.desc[0..75] %>...
			</p>
		</div>
		
		<div style="float:right;padding: 5px;">
			<%= image_tag server.avatar.url(:thumb), :style => "border: 1px solid black" if !server.avatar.nil?  %>
			<br/>
			<%= link_to 'Edit server', edit_server_path(server) %>
		</div>	
		
	</div>
	
	<!-- Info Collapse Div -->
		
	<div id="info_server_<%= server.id%>" style="display:none; overflow: auto; border: 1px solid green; border-top:none; width:90%; margin-left:20px; padding: 10px; padding-top:10px; background-color: white;">
	</div>	

	<script type="text/javascript"> 
 		animatedcollapse.addDiv('div_server_<%= server.id%>', 'fade=1,height=160px')
		animatedcollapse.addDiv('info_server_<%= server.id%>', 'fade=1,height=400px')
	</script>

	<% end %> <!-- End Server Loop -->
</div> <!-- End Rack Div -->
<br/>
<% end %>

<br />

[<%= link_to 'New Server', new_server_path %>]
[<%= link_to 'New Rack', new_server_rack_path %>]
<%= render 'servers/ping_all' %>



<!-- Collapse Divs init -->
<script type="text/javascript"> 
 animatedcollapse.ontoggle=function($, divobj, state){ 	
}
animatedcollapse.init()


function collapseServer(id){
	
	animatedcollapse.toggle("div_server_"+id); 
	animatedcollapse.hide("info_server_"+id);
	
	//Border manager
	animatedcollapse.ontoggle=function($, divobj, state){
		
		if(divobj.id.indexOf("div_server") < 0)
			return; 		
		id = divobj.id.substr(divobj.id.lastIndexOf("_")+1,divobj.id.length)
		
		if( state == "block"){
			$("#server_"+id).css("border","1px solid green")	
			$("#server_"+id).css("border-bottom","none")
			
			$("#div_server_"+id).css("border","1px solid green")	
			$("#div_server_"+id).css("border-top","none")			
		}else{
			$("#server_"+id).css("border","none")
			$("#div_server_"+id).css("border","none")			
		}
	}
}

</script>

app/views/server_racks/new.html.erb
<h1>New server_rack</h1>

<%= render 'form' %>

<%= link_to 'Back', server_racks_path %>

app/views/server_racks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @server_rack.name %>
</p>

<p>
  <b>Location:</b>
  <%= @server_rack.location %>
</p>


<p>
  <b>Contact email:</b>
  <%= @server_rack.contact_email %>
</p>


<p>
  <b>Desc:</b>
  <%= @server_rack.desc %>
</p>


<%= link_to 'Edit', edit_server_rack_path(@server_rack) %> |
<%= link_to 'Back', server_racks_path %>