config/routes.rb
RapaNui::Application.routes.draw do
  

  match 'servers/:id/ping' => 'servers#ping'
  match 'servers/:id/disks' => 'servers#disks', :as => "servers_disks"
  match 'servers/telnet/:id/:p' => 'servers#telnet', :as => "servers_telnet"
  match 'servers/command/:id/:cmd' => 'servers#command', :as => "servers_command"

  root :to => "server_racks#index"

  resources :servers do
    collection do
      get :search, :telnet
    end
  end
   
  resources :accounts do
    collection do
      get :login, :logout
      post :doLogin
    end
  end
   
  resources :types

  resources :operational_systems

  resources :os

  resources :server_racks

  resources :servers
  

end

app/models/server.rb
require 'net/telnet'

class Server < ActiveRecord::Base
  
  scope :all, order(:name)
  
  belongs_to :type
  belongs_to :server_rack
  belongs_to :operational_system
  belongs_to :depends_from, :class_name => "Server", :foreign_key => "dependent_server_id"
  
  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }

  validates_presence_of :name, :ip
  validates_uniqueness_of :ip, :message => "IP address is already in use"
  validates_uniqueness_of :name, :message => "Name is already in use"
  
  validate :monitor_validation

  def monitor_validation
      errors.add(:contact_email, "To monitoring, you need to fill contact e-mail") if (ping_monitor or telnet_monitor) && contact_email.empty?
      errors.add(:ports, "To monitoring, you need to fill the services ports") if (telnet_monitor) && ports.empty?
  end
  
  def ping
    ping = Net::Ping::ICMP.new(self.ip)
    ping_time = Time.now
    ping_alive = ping.ping
    ping_time = (Time.now - ping_time) * 1000.0
  
    return false, "Off" if !ping_alive    
    return true, "#{ ping_time.round(2) } ms"       
  end
  
  
  def telnet (port)
    
    str_result = ""
    begin
      localhost = Net::Telnet::new("Host" => self.ip,
                                   "Port" => port, 
                                   "Timeout" => 7,
                                   "Prompt" => /[$%#>] \z/n)  { |c| str_result +=  c }
                                   
     rescue Errno::ECONNREFUSED
       return false,"Connection Refused!" 
     ensure 
       localhost.close unless localhost.nil?
     end
     
     return false, "Fail" if str_result.index("Connected").nil?
     
     return true, "Connected!"
     
  end
  
   
  
  def ssh(command)
	begin
		result = ""
  	  	Net::SSH.start(self.ip, self.username,:password => self.password, :port => self.ssh_port) do |ssh|
			result = ssh.exec!(command)
		end
		return true, result
	rescue StandardError => bang
		puts bang.inspect
  		return false, "Error : " << bang.inspect
	end	  	
  end
  
  
  def disks

  	str_result = ""
	file_systems = Array.new
 
	result = self.ssh "df"  
	
	if result[0]
		splitted =  result[1].split("\n")
			  splitted.delete_at 0 
			  splitted.each { |line| 
			
				    file_system = line.split(" ")[0]
				    mounted_on  = line[/%.*/][/\/.*/]
				    capacity    = line[/..[0-9]%/]
				    capacity    = capacity[0,capacity.length-1]
				    
				    str_temp = file_system << " (" << mounted_on << ")\t"
				    str_result << str_temp << " " << capacity << "%\n" 
				    file_systems << Hash["file_system" => str_temp, "capacity" => capacity]
			}
		return true, str_result, file_systems	
	else		
		return false, result[1]
	end    
   end
  
  
end

app/controllers/servers_controller.rb
require 'rubygems'

class ServersController < ApplicationController
  
  before_filter :filter
  respond_to :html, :xml, :js
    
   def search
     q = "%#{params[:search]}%"
     @servers = Server.where("servers.name LIKE ? or servers.ip LIKE ? or servers.desc LIKE ? ", q, q, q).order(:name)
     respond_with @servers     
   end
   
   def telnet     
     @server = Server.find(params[:id])
     @port = params[:p]
     @str_result = @server.telnet(@port)[1] # getting second parameter from result (!), the first one is a boolean
   end
   
   
  # GET /servers
  # GET /servers.xml
  def index
    @servers = Server.all

    respond_with @servers 
  end

  # GET /servers/1
  # GET /servers/1.xml
  def show
    @server = Server.find(params[:id])

    respond_with @server
  end

  # GET /servers/new
  # GET /servers/new.xml
  def new
    @server = Server.new

    respond_with @server
  end

  # GET /servers/1/edit
  def edit
    @server = Server.find(params[:id])
  end
  

  
  # GET /servers/1/ping
  def ping
  	@server = Server.find(params[:id])
    @str_result = @server.ping[1] # getting second parameter from result (!)   
  end
 
   # GET /servers/1/disks
  def disks
    
	@server = Server.find(params[:id])
	result  = @server.disks
	if result[0]
	  @str_result = result[1]
	  @file_systems = result[2]
	else
	  @str_result = result[1]
	end
	
  end
  
  
  
  
  
  # GET /servers/1/command
  def command
    
    valid_commands = Hash[
    	"top"      => "TERM=linux & top -b -n 1",
    	"freem"    => "free -m",
    	"who"      => "who",
    	"ifconfig" => "ifconfig",
    	"netstat"  => "netstat",
    	"cpuinfo"  => "cat /proc/cpuinfo",
    	"du"       => "du -h --max-depth=1 /",
    	"uptime"   => "uptime"
    ]
    
    cmd = valid_commands[params[:cmd]]
        
	@server = Server.find(params[:id])
	result = @server.ssh  cmd 
	@str_result = result[1]
	
  end
  
  
 
   
  

  # POST /servers
  # POST /servers.xml
  def create
    @server = Server.new(params[:server])

    respond_to do |format|
      if @server.save
        format.html { redirect_to(@server, :notice => 'Server was successfully created.') }
        format.xml  { render :xml => @server, :status => :created, :location => @server }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @server.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /servers/1
  # PUT /servers/1.xml
  def update
    @server = Server.find(params[:id])

    respond_to do |format|
      if @server.update_attributes(params[:server])
        format.html { redirect_to(@server, :notice => 'Server was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @server.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /servers/1
  # DELETE /servers/1.xml
  def destroy
    @server = Server.find(params[:id])
    @server.destroy

    respond_to do |format|
      format.html { redirect_to(servers_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/servers_helper.rb
module ServersHelper
end

app/views/servers/_form.html.erb
<%= form_for @server, :html => { :multipart => true } do |f| %>
  <% if @server.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@server.errors.count, "error") %> prohibited this server from being saved:</h2>

      <ul>
      <% @server.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<fieldset>
	<legend>Info</legend>
	
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
<div class="field">
	 <%= f.label "Server image or photo" %><br />
	<%= f.file_field :avatar %>
</div>

  <div class="field">
    <%= f.label :desc %><br />
    <%= f.text_area :desc, :rows => 6 %>
  </div>

  <div class="field">
    <%= f.label :type_id %><br />
    <%=f.select :type_id, Type.all.collect { |i| [i.name, i.id] }%><br>
  </div>

  <div class="field">
    <%= f.label :server_rack_id %><br />
  	<%=f.select :server_rack_id, ServerRack.all.collect { |i| [i.name, i.id] }%><br>
  </div>

<div class="field">
    <%= f.label "Depends of:" %><br />
    <%=f.select :dependent_server_id, Server.all.collect { |i| [i.name, i.id] }, :include_blank => true %><br>
  </div>

<div class="field">
    <%= f.label :operational_system_id %><br />
   	<%=f.select :operational_system_id, OperationalSystem.all.collect { |i| [i.name, i.id] }%><br>
  </div>

</fieldset>

<fieldset>
	<legend>Access</legend>
	
  <div class="field">
    <%= f.label :ip %><br />
    <%= f.text_field :ip %>
  </div>

  <div class="field">
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </div>

  <div class="field">
    <%= f.label :password %><br />
    <%= f.text_field :password, :type => :password %>
  </div>

  <div class="field">
    <%= f.label :ssh_port %><br />
    <%= f.text_field :ssh_port %>
  </div>

  <div class="field">
    <%= f.label "Ports with blank space separator (ex: web:80 oracle:1031)" %><br />
    <%= f.text_field :ports, :size => 100 %>
  </div>

  <div class="field">
    <%= f.label "Enabled?" %><br />
    <%= f.check_box :alive %>
  </div>
</fieldset>

  

<fieldset>
	<legend>Contact and monitoring</legend>
  <div class="field">
    <%= f.label :contact %><br />
    <%= f.text_field :contact %>
  </div>
  <div class="field">
    <%= f.label :contact_email %> (Use "," to add more e-mails)<br />
    <%= f.text_field :contact_email, :size => 100 %>
  </div>
 <div class="field">
    <%= f.label :ping_monitor %><br />
    <%= f.check_box :ping_monitor %>
  </div>
  <div class="field">
    <%= f.label :telnet_monitor %><br />
    <%= f.check_box :telnet_monitor %>
  </div>
  <div class="field">
    <%= f.label :disk_monitor %><br />
    <%= f.check_box :disk_monitor %>
  </div>
</fieldset>

  <div class="field">
    <%= f.label :hw_specs %><br />
    <%= f.text_area :hw_specs, :rows => 4 %>
  </div>
  <div class="field">
    <%= f.label :visible_label %><br />
    <%= f.text_field :visible_label %>
  </div>
  <div class="field">
    <%= f.label :model %><br />
    <%= f.text_field :model %>
  </div>
  <div class="field">
    <%= f.label :warranty_expiration %><br />
    <%= f.date_select :warranty_expiration %>
  </div>
  <div class="field">
    <%= f.label :serial_number %><br />
    <%= f.text_field :serial_number %>
  </div>
  
  
  <div class="field">
    <%= f.label :application_test_script %><br />
    <%= f.text_area :application_test_script %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/servers/_ping_all.html.erb
<script>
function pingAll(){

	try{
		$(".alive_td").html("..");
		
		var alives = $(".alive_link");
				
		for(var i=0; i < alives.length ;i++){
			try{
				$.ajax({  
                type: "GET", url: alives[i].href+"" , complete: function(data){ 
               	     eval(data.responseText);
                	}  
            	});	
			}catch(e){alert(e)}
		}	
	}catch(e){
		alert(e);
	}	

}



//pingAll();
</script>

app/views/servers/_searchform.html.erb
<div style="float:right; margin-right:24%; text-align:right;">
<form action="/servers/search">
	<label for="search">Search
	<span style="font-size:9px; color: #A0A0A0"></span>
	<input type="text" size="30" id="search" value="name or ip or desc" onfocus="this.value=''" name="search"/>
	</label>
	<button type="submit">Go</button>
</form>
</div>

app/views/servers/command.js.erb
$('#info_server_<%=@server.id%>').html ("<div id='cmd'><pre><%= @str_result.html_safe.gsub(/\n/,'<br/>').html_safe %></pre></div>");
$('#cmd').css('font-family' , 'Courier New');



animatedcollapse.show('info_server_<%= @server.id%>');

app/views/servers/disks.js.erb
$('#info_server_<%=@server.id%>').html ("<pre id='courier'><%= @str_result.html_safe.gsub(/\n/,'<br/>').html_safe %></pre>");
$('#courier').css('font-family' , 'Courier New');
animatedcollapse.show('info_server_<%= @server.id%>');



<% counter = 0%>
<% @file_systems.each { |partition| %>
<% counter = counter + 1 %>

try{
		$('#info_server_<%=@server.id%>').append("<div id='chart<%=@server.id%>_<%=counter%>' style='width:270px;heigth:270px;float:left;'></div>")
		
         var chart<%=@server.id%>;
         
          $(function() {
            chart<%=@server.id%> = new Highcharts.Chart({
              chart: {
                renderTo: 'chart<%=@server.id%>_<%=counter%>'
              },
              title: {
                text: "<%=partition["file_system"]%>"
              },
              defaultSeriesType: {
                text: "Pie" 
              },
              plotOptions: {
               pie: {
                  allowPointSelect: true,
                  cursor: 'pointer',
               }
              },
              tooltip: {
               formatter: function() {
                    return  Math.round(this.percentage)+'%';
                 }
              },
              
              
              
              
              
              series: [{
                <%
                  rdata = ""
           		  rdata << "['free', #{100-Integer(partition["capacity"])}],"
                  rdata << "['used', #{partition["capacity"].strip}],"
                  rdata = rdata[0,rdata.length-1]
                %>
              
                data: [<%=rdata%>],   
                type: "pie"        
              }]
            });
          });
}catch(e){
 alert(e)
}

<% } %>


$('.highcharts-title').attr({y : "50"});
//$('.highcharts-point').attr({transform : "translate(80, -50)"});
//$('.highcharts-legend').attr({transform : "translate(43.7891, 230)"});

//alert($('#info_server_<%=@server.id%>').html())

app/views/servers/edit.html.erb
<h1>Editing server</h1>

<%= render 'form' %>

<%= link_to 'Show', @server %> |
<%= link_to 'Back', servers_path %>

app/views/servers/index.html.erb
<%= render 'searchform' %>

<h1>Servers</h1>

<div style="border: 1px solid #AAFFAA; width: 75%; padding: 2px; margin:5px; background-color: #EFFFEF">

<table>
  <tr >
    <th>Name</th>    
    <th>Type</th>
    <th>Rack</th>
    <th>Ip</th>
    <th>Alive</th>
    <th>Os</th>
    <th>Contact</th>
    <th>Model</th>

  </tr>
<% c = 0%>
<% @servers.each do |server| %>
  <% c+=1 
	 if(c%2==0) 
		clazz = "odd"
	 else 
		clazz = "even"
	 end	
	%>
	
  <tr class="<%=clazz%>" title="<%= server.desc %>">
    <td style="font-weight:bold"><%= link_to server.name, server %></td>   
    <td><%= server.type.name %></td>
    <td><%= server.server_rack.name %></td>
    <td><%= server.ip %></td>
    <td id="alive<%=server.id%>" class="alive_td" style="position: relative;">... </td>
    <td><%= server.operational_system.name %></td>
    <td><a href="mailto:<%= server.contact_email %>"><%= server.contact %></a></td>
	<td><%= server.model %></td>
    <td><%= link_to 'Edit', edit_server_path(server) %></td>
    <td><%= link_to 'Destroy', server, :confirm => 'Are you sure?', :method => :delete %></td>
    <td><%= link_to 'Ping', server_path(server)+"/ping" , :remote => true , :class => "alive_link" %><td>
  </tr>
<% end %>
</table>

</div>
<br />


<%= link_to 'New Server', new_server_path %>
<a href="#" onclick="pingAll();"  data-remote="true">Ping All</a>

<%= render 'ping_all' %>

app/views/servers/new.html.erb
<h1>New server</h1>

<%= render 'form' %>

<%= link_to 'Back', servers_path %>

app/views/servers/ping.js.erb
$('#alive<%= @server.id %>').html ("<%= @str_result %>");

if("<%= @str_result %>" == "Off" )
	$('#alive<%= @server.id %>').addClass( "status_false")
else
	$('#alive<%= @server.id %>').addClass("status_true")


$('#alive<%= @server.id %>').effect('highlight', {}, 1000);

app/views/servers/search.html.erb
<%= render 'searchform' %>
   	
<div style="border: 1px solid #AAFFAA; width: 70%; padding: 8px; margin:5px; background-color: #EFFFEF">

<% @servers.each do |server| %>

<div title=" <%= server.desc %>" style="border: 1px solid EEFFEE; padding: 10px; margin:5px; padding-left:50px; background-color: #FFFFFF">
    
	<span style="font-weight: bold; margin-right: 10px;"><%= server.name %></span>
 	<span style="margin-right: 10px;"><%= server.ip %></span> 	
	<%= link_to 'Show', server %>
	<span style="margin-left: 10px;" class="status_<%= server.alive%>"><%= server.alive ==  TRUE ? "On-line" : "Off-line" %></span>

</div>

<% end %>

</div>


<br />

app/views/servers/show.html.erb
<script>

 function togglePWD(){
 	if($('#btnPWD').html() == 'Show'){
 		$('#pwd').css('display','block');
 		$('#btnPWD').html('Hide');
 	}else{
 		$('#pwd').css('display','none');
 		$('#btnPWD').html('Show');
 	}
 }

</script>


<p id="notice"><%= notice %></p>

<p alt="<%= @server.desc %>">
  <h2><%= @server.name %></h2>
</p>

<%= image_tag @server.avatar.url(:medium) %>

<p>
  <b>Desc:</b>
  <%= @server.desc %>
</p>

<p>
  <b>Type:</b>
  <%= @server.type.name %>
</p>

<p>
  <b>Rack:</b>
  <%= @server.server_rack.name %>
</p>

<p>
  <b>Depends of:</b>
  <%= link_to @server.depends_from.name, @server.depends_from  if(!@server.depends_from.nil?)  %>
</p>

<p>
  <b>Ip:</b>
  <%= @server.ip %>
</p>

<p>
  <b>Username:</b>
  <%= @server.username %>
</p>

<p>
  <b>Password:</b>
  <p id="pwd" style="display:none"><%= @server.password %></p>
  <button id="btnPWD" type="button" onclick="togglePWD();">Show</button>
</p>

<p>
  <b>SSH Port:</b>
  <%= @server.ssh_port %>
</p>

<p>
 <b>Services:</b>
<% 
if(!@server.ports.nil?)
@server.ports.split(" ").each do |port|
serv =  port.split(":")[0] 
port = port.split(":")[1] %>
   
<li>
<%= serv %> @ <%= link_to port, servers_telnet_url(params = {:id => @server, :p => port}), :remote => true %>  <span id="telnet_<%=@server.id%>_<%=port%>"></span>
</li>

<%
end
end
%>

</p>

<p>
  <b>Ping Monitoring:</b>
  <%= @server.ping_monitor %>
</p>

<p>
  <b>Telnet Monitoring:</b>
  <%= @server.telnet_monitor %>
</p>

<p>
  <b>Alive:</b>
  <%= @server.alive %>
</p>




<p>
  <b>Os:</b>
  <%= @server.operational_system.name %>
</p>

<p>
  <b>Contact:</b>
  <%= @server.contact %>
</p>

<p>
  <b>Contact email:</b>
  <%= @server.contact_email %>
</p>

<p>
  <b>Hw specs:</b>
  <%= @server.hw_specs %>
</p>

<p>
  <b>Visible label:</b>
  <%= @server.visible_label %>
</p>

<p>
  <b>Model:</b>
  <%= @server.model %>
</p>

<p>
  <b>Warranty expiration:</b>
  <%= @server.warranty_expiration %>
</p>

<p>
  <b>Serial number:</b>
  <%= @server.serial_number %>
</p>


<p>
  <b>Alive:</b>
  <span id="alive<%= @server.id %>">...</span>
</p>





<%= link_to 'Edit', edit_server_path(@server) %> |
<%= link_to 'Ping', server_path(@server)+"/ping" , :remote => true , :class => "alive_link" %>|
<%= link_to 'Back', servers_path %>


<script>

	$(".alive_link").click();	

</script>

app/views/servers/telnet.js.erb
$('#telnet_<%= @server.id %>_<%= @port %>').html ("<%= @str_result %>");

if("<%= @str_result %>" == "Connected!" )
	$('#telnet_<%= @server.id %>_<%= @port %>').addClass( "status_true")
else
	$('#telnet_<%= @server.id %>_<%= @port %>').addClass("status_false")

$('#telnet_<%= @server.id %>_<%= @port %>').effect('highlight', {}, 1000);